//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.23 at 08:51:41 AM IST 
//


package com.codefox.blog.api;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/blog-api}answerId"/>
 *         &lt;element ref="{http://www.example.org/blog-api}answerData"/>
 *         &lt;element ref="{http://www.example.org/blog-api}user"/>
 *         &lt;element ref="{http://www.example.org/blog-api}question"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "answerId",
    "answerData",
    "user",
    "question"
})
@XmlRootElement(name = "answer")
@Entity
public class Answer {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    protected int answerId;
    
    
    @XmlElement(required = true)
    @Column(nullable=false)
    protected String answerData;
    
    @Column(nullable=false)
	protected int userId;
    
    @Column(nullable=false)
	protected int questionId;
    
    @XmlElement(required = true)
    @ManyToOne
    protected User user;
    
    @XmlElement(required = true)
    @ManyToOne(cascade=CascadeType.ALL)
    protected Question question;
    

    /**
     * Gets the value of the answerId property.
     * 
     */
    public int getAnswerId() {
        return answerId;
    }

    /**
     * Sets the value of the answerId property.
     * 
     */
    public void setAnswerId(int value) {
        this.answerId = value;
    }

    /**
     * Gets the value of the answerData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerData() {
        return answerData;
    }

    /**
     * Sets the value of the answerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerData(String value) {
        this.answerData = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the question property.
     * 
     * @return
     *     possible object is
     *     {@link Question }
     *     
     */
    public Question getQuestion() {
        return question;
    }

    /**
     * Sets the value of the question property.
     * 
     * @param value
     *     allowed object is
     *     {@link Question }
     *     
     */
    public void setQuestion(Question value) {
        this.question = value;
    }

	@Override
	public String toString() {
		return "Answer [answerId=" + answerId + ", answerData=" + answerData + ", user=" + user + ", question="
				+ question + "]";
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getQuestionId() {
		return questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

}
